name: deta
description: A Dart package to interact with the HTTP API of the free services of the Deta plataform.
version: 0.0.1-beta
repository: https://github.com/yeikel16/deta-dart
homepage: https://github.com/yeikel16/deta-dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  equatable: ^2.0.3
  meta: ^1.7.0
  mocktail: ^0.2.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^2.4.0
