name: dio_client_deta_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies: 
  dio: ^4.0.4
  client_deta_api: ^0.0.2-dev.1
  
dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^2.4.0
  mocktail: ^0.2.0
