name: http_client_deta_api
description: Implementation of the client_deta_api package using the http package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  client_deta_api: ^0.0.2-dev.1
  http: ^0.13.4

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
